### ISSUE TITLE
JSON file incorrect parsed ?

### ISSUE THREAD

**Issue by rbarzic** [LudwigCRON/pywave#40]
This file:
[std_memory_interface_v3.json.gz](https://github.com/LudwigCRON/undulate/files/8125724/std_memory_interface_v3.json.gz)

is read correctly by wavedrom (npx wavedrom-cli -i std_memory_interface_v3.json -s test.png)

but fails with undulate:
undulate -f cairo-png --dpi 300 -i  std_memory_interface_v3.json  -o output.png
CRITICAL: Parsing Error detected: Expecting value at line 3

**Comment by LudwigCRON** [comment]
Hello Ronan,

Thank you for reporting this parsing issue.  The json format is strict but as wavedrom tolerate extra syntaxic sugar (single quotes string, trailing commas, ...) it is needed to preprocess json files.

In the file, the first "syntax error" is on 'me/req'. I did not have anticipated all characters.

The second type of errors are trailing commas.

 I will implement the fix and add a testcase:
- [x] update regex to support any utf8 char
- [x] update regex to support all possible trailing commas

**Comment by rbarzic** [comment]
Thanks !

**Comment by LudwigCRON** [comment]
With the latest commit the provided file can be generated
![std_memory_interface_v3](https://user-images.githubusercontent.com/2118740/155407457-6c5085d8-cae5-4a64-99e0-430cc42b92dd.png)
